name: Build EXE
on: [workflow_dispatch]

# This fixes the Node.js 20 deprecation warning
env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build Solution
        run: msbuild VMP-Imports-Deobfuscator.sln /p:Configuration=Release /p:Platform=x64

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: VMP-Deobfuscator-Exe
          # This pattern finds the exe in any subfolder's Release directory
          path: |
            **/Release/*.exe
            **/x64/Release/*.exe
            **/bin/Release/*.exe
